### ISSUE TITLE
Failed to boot firecracker VM, failed to fetchRepository?

### ISSUE THREAD

**Issue by bgoosman** [hocus-dev/hocus#73]
hocus-local-hocus-agent-1  | 2023-05-07T18:51:16.089Z [INFO] Booting firecracker VM with pid 254 took: 456.09 ms, TOTAL: 505.93 ms
hocus-local-hocus-agent-1  | 2023-05-07T18:51:18.255Z [WARN] firecracker process with pid 254 closed: 0
hocus-local-hocus-agent-1  | 2023-05-07T18:52:11.437Z [WARN] Activity failed {
hocus-local-hocus-agent-1  |   error: FetchError: The request failed and the interceptors did not return an alternative response
hocus-local-hocus-agent-1  |       at DefaultApi.BaseAPI.fetchApi (/app/node_modules/firecracker-client/dist/runtime.js:100:31)
hocus-local-hocus-agent-1  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hocus-local-hocus-agent-1  |       at DefaultApi.request (/app/node_modules/firecracker-client/dist/runtime.js:136:26)
hocus-local-hocus-agent-1  |       ... 5 lines matching cause stack trace ...
hocus-local-hocus-agent-1  |       at /app/agent.js:2259:16 {
hocus-local-hocus-agent-1  |     cause: TypeError: fetch failed
hocus-local-hocus-agent-1  |         at fetch (/app/node_modules/undici/index.js:105:13)
hocus-local-hocus-agent-1  |         at processTicksAndRejections (node:internal/process/task_queues:96:5)
hocus-local-hocus-agent-1  |         at DefaultApi.BaseAPI.fetchApi (/app/node_modules/firecracker-client/dist/runtime.js:84:28)
hocus-local-hocus-agent-1  |         at DefaultApi.request (/app/node_modules/firecracker-client/dist/runtime.js:136:26)
hocus-local-hocus-agent-1  |         at DefaultApi.createSyncActionRaw (/app/node_modules/firecracker-client/dist/apis/DefaultApi.js:83:26)
hocus-local-hocus-agent-1  |         at DefaultApi.createSyncAction (/app/node_modules/firecracker-client/dist/apis/DefaultApi.js:96:9)
hocus-local-hocus-agent-1  |         at FirecrackerService.shutdownVM (/app/agent.js:3817:5)
hocus-local-hocus-agent-1  |         at FirecrackerService.withVM (/app/agent.js:3798:9)
hocus-local-hocus-agent-1  |         at /app/agent.js:4082:7
hocus-local-hocus-agent-1  |         at /app/agent.js:2259:16 {
hocus-local-hocus-agent-1  |       cause: [Error]
hocus-local-hocus-agent-1  |     }
hocus-local-hocus-agent-1  |   },
hocus-local-hocus-agent-1  |   durationMs: 55931,
hocus-local-hocus-agent-1  |   isLocal: false,
hocus-local-hocus-agent-1  |   attempt: 1,
hocus-local-hocus-agent-1  |   namespace: 'default',
hocus-local-hocus-agent-1  |   taskToken: '...',
hocus-local-hocus-agent-1  |   workflowId: '271718a2-c2e1-4e43-8ffc-695c43e5c6d0',
hocus-local-hocus-agent-1  |   workflowRunId: '6d4504b2-5b2d-4d8b-89d6-961d0605af71',
hocus-local-hocus-agent-1  |   workflowType: 'runBuildfsAndPrebuilds',
hocus-local-hocus-agent-1  |   activityId: '2',
hocus-local-hocus-agent-1  |   activityType: 'fetchRepository',
hocus-local-hocus-agent-1  |   taskQueue: 'main'
hocus-local-hocus-agent-1  | }

**Comment by bgoosman** [comment]
I'm on bitbucket

**Comment by hugodutka** [comment]
It looks like the VM that fetchRepository uses was killed before the Hocus agent could shut it down normally. This could have happened because your host was out of memory and the OOM killer did its thing. Are you running it on a system that has less than 8-16GB of free RAM? Hocus is currently very memory hungry and we are working on reducing that.

If memory is the culprit, an easy fix would be creating a swap file on your host. I would suggest 16GB of size. https://linuxize.com/post/create-a-linux-swap-file/

**Comment by bgoosman** [comment]
Hmm I should have 64 GB RAM total, on an Ubuntu 20.04 Focal OS.
![image](https://user-images.githubusercontent.com/1022779/236838469-1c7f55aa-c676-4c94-a129-72b638f0378c.png)

```sh
top - 15:38:46 up 20:48,  1 user,  load average: 0.23, 0.55, 0.54
Tasks: 267 total,   1 running, 266 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  64241.8 total,  35695.6 free,    466.1 used,  28080.1 buff/cache
MiB Swap:  32735.0 total,  32735.0 free,      0.0 used.  63065.2 avail Mem
```

I forgot I got this warning which I didn't know what to do with. (Sorry, not a linux pro 😅)

```sh
> HOCUS_HOSTNAME="x" ops/bin/local-up.sh
HOCUS_HOSTNAME="x" ops/bin/local-up.sh
[WARNING] Host kernel *might* be too old. If you encounter issues with nested virtualization please first try running Hocus on at least the 5.10 kernel
Building docker images 👷📦
Building vm-builder done in 1.32 s ✅
Building db-autosetup done in 0.52 s ✅
Building keycloak done in 0.80 s ✅
Building temporal-codec done in 1.34 s ✅
Building ui done in 0.82 s ✅
Building agent done in 0.88 s ✅
Pulling docker images 📥 - ✅ in 1.26 s
Building MicroVMs 👷🖥️ - ✅ in 4.21 s
Seeding the DB 🌱 - ✅ in 0.77 s
Starting the DB 📙 - ✅ in 2.00 s
Starting Keycloak 🔑 - ✅ in 11.01 s
Starting Temporal ☁️  - ✅ in 12.52 s
Starting Hocus 🧙🪄  - ✅ in 3.98 s

You may access Hocus here: http://x:3000/ Creds: dev/dev
Keycloak: http://x:4200/ Creds: admin/admin
Temporal: http://x:8080/

To delete all data ./ops/bin/local-cleanup.sh
To get debug logs: ./ops/bin/local-cmd.sh logs
To stop the deploy: ./ops/bin/local-cmd.sh down
```

**Comment by gorbak25** [comment]
@bgoosman 
- What filesystem are you running on, how much free storage is available on the system?
- Are you running plain docker, docker in user namespaces or podman ?
- How large is your bitbucket repository? 
- I've checked on my setup that Hocus works well with Bitbucket, the issue must lie somewhere in the setup.
- Do you have an hocus.yml file in the repository?
